#!/bin/bash

GREEN='\e[1;32m'
CYAN='\e[36m'
YELLOW='\e[1;33m'
RED='\e[31m'
RESET='\e[0m'

caeser() {
	ab=$(tr [:upper:] [:lower:] <<< "$1")
	
	for i in b c d e f g h i j k l m n o p q r s t u v w x y z; do
		j=$(tr [bcdefghijklmnopqrstuvwxyza] [a-z] <<< "$i")
		kj=$(tr "[a-z]" "[$i-za-$j]" <<< "$ab")
		echo -e "${GREEN}   $kj${RESET}"
		echo -e "${CYAN}\n---\n${RESET}"
	done
}

usg="${RED}Usage: csrcipher 'text' — brute-forces all Caesar cipher shifts on the input string.${RESET}"
if [[ -z "$1" ]]; then
	echo "$usg"
else
	echo -e "${YELLOW}***\n\n TWENTYFIVE CAESAR SHIFTS BELOW:${RESET}"
	echo -e "${CYAN}\n---\n${RESET}"
	caeser "$1"
	echo -e " ${YELLOW}LOOK FOR HUMAN READABLE TEXTS ABOVE.\n\n***${RESET}"
fi
